<?php
// Begin session
session_start();
?>

<div class="navbar">
    <img src="images/logo.png" class="logo" alt="company logo">
    <ul>
        <li><a href="./"><span class="home">Home</span></a></li>
        <li><a href="jobs.php"><span class="jobs"> Jobs</span></a></li>
        <li><a href="apply.php"><span class="apply">Apply</span></a></li>
        <li><a href="about.php"><span class="about"> About</span></a></li>
        <li><a href="enhancements.php"><span class="enhancements">Enhancements</span></a></li>
    </ul>
</div>